### PR TITLE
TAJO-1744: Porting bash shell scripts to Windows command shell scripts.

### PR DESCRIPTION
**Pull request by hys9958**
Hi,
I have ported to CMD the bash shell.
And i attach pdf to explain about getting started for Windows Tajo to ticket(TAJO-1744) of Apache tajo.
https://issues.apache.org/jira/secure/attachment/12750713/tajo_cmd.pdf

- conf
    - tajo-env.cmd
- bin
    - start-tajo.cmd
    - stop-tajo.cmd
    - tajo-daemon.cmd
    - tajo.cmd
    - tajo-config.cmd
    - tsql.cmd

### CODE REVIEW

**Comment by jihoonson** [comment]
@hys9958, thanks for your work. Would you trigger ci again?

**Comment by hys9958** [comment]
@jihoonson, of couse.
I have updated a tajo.cmd file to add some log message.
So, May be run CI.

**Comment by dkhwangbo** [comment]
@hys9958 
Thanks for your effort.
I'm trying to check suitability of your work
and some inappropriate operation is occured like below picture.
capture01
after quit of tsql, some other word is printed.
Please check this part.

**Comment by jihoonson** [comment]
Honestly, it seems that this problem is not directly related to this ticket. It would be better to book at another jira, I think.

**Comment by dkhwangbo** [comment]
Testing this commit is done. I can run tajo in Windows 7 via above files.
I also test tsql.cmd via TPC-H set in same environment. TAJO can run all query of this set.

**Comment by jihoonson** [comment]
@dkhwangbo, thank you for your test. 
Here is my +1.
@hys9958, thank you for your work.

**Pull request closed without merging**
