### PR TITLE
TAJO-2156: Create GeoIP functions taking various types instead of INET4 type 

### PR DESCRIPTION
**Pull request by eminency**

### CODE REVIEW

**Comment by jinossy** [comment]
This changes should be added tests.
If you change GeoIP to GeoIP2, it would be better for tests.
please see the lincese and csv database for testing

http://maxmind.github.io/GeoIP2-java
https://dev.maxmind.com/geoip/geoip2/geoip2-city-country-csv-databases

**Comment by eminency** [comment]
Hi, @jinossy 

Other geoip functions(old ones) have not had a test.
I think it is because of license problem - GeoIP library is set as 'provided' in pom.xml, so test code doesn't work.

Is that wrong?

**Comment by jinossy** [comment]
The Initial code did not add a tests. because geoip is GPL.
Now, geoip function is breaking changes. we should add a tests.
GeoIP2 is Apache 2.0 license. so we can add the module and tests in tajo binary

**Comment by eminency** [comment]
Oh, I got it.

**Comment by jinossy** [comment]
@eminency 
Geoip2 seems to need to add a mock DataReader.
If we add a geoip2 function by new jira issue, It would be better. What do you think?

**Comment by eminency** [comment]
Good suggestion. I will separate it.

**Comment by eminency** [comment]
Separated issues and refined code.

**Comment by jihoonson** [comment]
This patch looks good to me.
@jinossy do you have any other comments?

**Comment by jinossy** [comment]
+1 LGTM

**Comment by jihoonson** [comment]
+1 ship it!

**Comment by eminency** [comment]
Thanks for the review.
I'll commit.

**Pull request closed without merging**
