### PR TITLE
TAJO-1741: Two tables having same time zone display different timestamps

### PR DESCRIPTION
**Pull request by eminency**
includeTimezone flag is for TIMESTAMPZ type, so changed to 'false'

[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/699)

### CODE REVIEW

**Comment by hyunsik** [comment]
+1
The change looks straightforward. I'll change your comments into a java doc format before committing.

**Comment by hyunsik** [comment]
@eminency 

I missed one thing. Could you add insert tests using timezone?

**Comment by eminency** [comment]
@hyunsik 

Thank you for review.
I applied your suggestion right before.

**Comment by hyunsik** [comment]
+1
The patch looks good to me, and it looks enough for the unit test to verify this bug fix.

**Pull request closed without merging**
