### PR TITLE
TAJO-1300: Merge the index branch into the master branch

### PR DESCRIPTION
**Pull request by jihoonson**
I think that ```index_support``` branch is ready to be merged into ```master```.
In this branch, I've developed Tajo to support index feature. Here are some highlight features.

* Support CREATE / DROP INDEX statement (TAJO-836, TAJO-837)
* Improve query planner to utilize index if possible (TAJO-838)
* Support index metadata backup and restore (TAJO-1301, TAJO-1302)

There remains some additional features to improve the support on index including https://issues.apache.org/jira/browse/TAJO-1164. I'll proceed them in https://issues.apache.org/jira/browse/TAJO-835.

[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/651)

### CODE REVIEW

**Comment by blrunner** [comment]
Hi @jihoonson 

I found that TajoMaster printed a error message when executing *\d* command on tsql as follows.

# Tsql

```
default> \d nation;

table name: default.nation
table uri: hdfs://localhost:9010/tpch/nation
store type: TEXT
number of rows: unknown
volume: 2.2 kB
Options: 
	'textfile.delimiter'='|'
	'text.delimiter'='|'

schema: 
n_nationkey	INT8
n_name	TEXT
n_regionkey	INT8
n_comment	TEXT

```

# TajoMaster

```
2015-07-24 15:29:08,821 ERROR org.apache.tajo.catalog.CatalogServer: 
Stack Trace:
org.apache.tajo.exception.TajoInternalError: internal error: no error message for UNDEFINED_INDEX
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:119)
	at org.apache.tajo.exception.ReturnStateUtil.returnError(ReturnStateUtil.java:79)
	at org.apache.tajo.exception.ReturnStateUtil.errUndefinedIndex(ReturnStateUtil.java:176)
	at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.existIndexesByTable(CatalogServer.java:1136)
	at org.apache.tajo.catalog.AbstractCatalogClient.existIndexesByTable(AbstractCatalogClient.java:571)
	at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.existIndexesForTable(TajoMasterClientService.java:1066)
	at org.apache.tajo.ipc.TajoMasterClientProtocol$TajoMasterClientProtocolService$2.callBlockingMethod(TajoMasterClientProtocol.java:711)
```

**Comment by jihoonson** [comment]
@blrunner, thanks. This is a bug while applying the recent changes on error propagation. Since this exception is not exposed to users, I couldn't recognized it.
Anyway, I'll fix soon.

**Comment by blrunner** [comment]
OK, No problem. :-)

And if there is a message when executing *explain* command on tsql, this patch would be more good. Currently, I can't know whether index scan is applied or not before executing select statement as following:

```
default> create external table lineitem (L_ORDERKEY bigint, L_PARTKEY bigint, L_SUPPKEY bigint, L_LINENUMBER bigint, L_QUANTITY double, L_EXTENDEDPRICE double, L_DISCOUNT double, L_TAX double, L_RETURNFLAG text, L_LINESTATUS text, L_SHIPDATE text, L_COMMITDATE text, L_RECEIPTDATE text, L_SHIPINSTRUCT text, L_SHIPMODE text, L_COMMENT text) using text with ('textfile.delimiter'='|') location 'hdfs://localhost:9010/tpch/lineitem';
OK

default> create index l_orderkey_idx on lineitem (l_orderkey);

default> \set INDEX_ENABLED true

default> explain select count(*) from lineitem where l_orderkey = 1;
explain
-------------------------------
GROUP_BY(3)()
  => exprs: (count())
  => target list: ?count (INT8)
  => out schema:{(1) ?count (INT8)}
  => in schema:{(0) }
(5 rows, 0.034 sec, 0 B selected)

default> select count(*) from lineitem where l_orderkey = 1;
Progress: 100%, response time: 0.581 sec
?count
-------------------------------
6
(1 rows, 0.581 sec, 2 B selected)
```

**Comment by blrunner** [comment]
I found that relative index functions of HiveCatalogStore just throws UnsupportedOperationException. Hive already provides relative index functions to client, for examples, createIndex, dropIndex, getIndex, alterIndex. Even if not in right now, you need to consider HiveCatalogStore implementation.

**Comment by jihoonson** [comment]
You are right. I will book those issues in other Jiras.

**Comment by blrunner** [comment]
I found that index scan just applied using an equals sign (=) in a predicate. If you add valid predicate operators for index scan and a few examples to document, it would be more helpful to users. :-)

**Comment by jihoonson** [comment]
Right, but it's not related to this issue.
Honestly, I've already created an issue for documentation (https://issues.apache.org/jira/browse/TAJO-1705).

**Comment by blrunner** [comment]
OK. I got it. :-)

**Comment by blrunner** [comment]
After pulling latest codes, I found another error message on tsql as following:

```
2015-07-24 17:12:00,767 ERROR org.apache.tajo.catalog.CatalogServer: 
Stack Trace:
java.lang.StackOverflowError
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:121)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
	at org.apache.tajo.exception.TajoRuntimeException.<init>(TajoRuntimeException.java:43)
	at org.apache.tajo.exception.ErrorMessages.getMessage(ErrorMessages.java:136)
```

This issue looks like an issue of the master branch without relevant to this PR. If you don't mind, could you recover relative codes? We need to book this issue with another JIRA issue.

**Comment by jihoonson** [comment]
That error is already fixed at https://github.com/apache/tajo/commit/98b841dd543866997c1d2e806dc0d3a40cf6beee.

**Comment by blrunner** [comment]
I removed existing codes and got latest source codes of this PR. *mvn clean install -Pparallel-test -DLOG_LEVEL=WARN -Dmaven.fork.count=2* have been finished successfully. But above situation is still reproduced. Could you check it again or recover it to as-found condition?

**Comment by jihoonson** [comment]
Thank. There is another problem at TajoDump. I've fixed it.

**Comment by blrunner** [comment]
+1

Thanks @jihoonson and I found that it worked successfully. 
Ship it. :)

**Comment by hyunsik** [comment]
+1
The patch looks good to me. Finally, we can merge it to master branch. Thank you for your effort.

**Comment by jihoonson** [comment]
I'm very happy with that I finally committed this patch. Thanks guys!

**Pull request closed without merging**
