### PR TITLE
TAJO-1928: Can't read parquet on hive meta

### PR DESCRIPTION
**Pull request by jinossy**

### CODE REVIEW

**Comment by jinossy** [comment]
Additionally, I’ve remove unnecessarily exception in alterTablespace of HiveCatalogStore
```
Stack Trace:
org.apache.tajo.exception.TajoRuntimeException: org.apache.tajo.exception.UnsupportedException: unsupported feature: Tablespace in HiveMeta
        at org.apache.tajo.catalog.store.HiveCatalogStore.alterTablespace(HiveCatalogStore.java:344)
        at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.alterTablespace(CatalogServer.java:397)
        at org.apache.tajo.catalog.AbstractCatalogClient.alterTablespace(AbstractCatalogClient.java:170)
        at org.apache.tajo.master.TajoMaster.checkBaseTBSpaceAndDatabase(TajoMaster.java:407)
        at org.apache.tajo.master.TajoMaster.serviceStart(TajoMaster.java:325)
        at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
        at org.apache.tajo.master.TajoMaster.main(TajoMaster.java:607)
Caused by: org.apache.tajo.exception.UnsupportedException: unsupported feature: Tablespace in HiveMeta
        ... 7 more
```

**Comment by jihoonson** [comment]
Hi @jinossy, thanks for your work.
I found a problem of this patch when creating a table of text format.
Here is the log.
```
default> create external table nation (
>     N_NATIONKEY bigint,
>     N_NAME text,
>     N_REGIONKEY bigint,
>     N_COMMENT text)
> using text with ('text.delimiter'='|') location 'hdfs://localhost:7020/tpch1/nation';
ERROR: internal error: TEXTFILE_INPUT

2015-10-15 11:18:06,362 ERROR org.apache.tajo.catalog.CatalogServer:
Stack Trace:
org.apache.tajo.exception.TajoInternalError: internal error: TEXTFILE_INPUT
        at org.apache.tajo.catalog.store.HiveCatalogStore.createTable(HiveCatalogStore.java:602)
        at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.createTable(CatalogServer.java:691)
        at org.apache.tajo.catalog.AbstractCatalogClient.createTable(AbstractCatalogClient.java:584)
        at org.apache.tajo.master.exec.CreateTableExecutor.create(CreateTableExecutor.java:111)
        at org.apache.tajo.master.exec.CreateTableExecutor.create(CreateTableExecutor.java:67)
        at org.apache.tajo.master.exec.DDLExecutor.execute(DDLExecutor.java:107)
        at org.apache.tajo.master.exec.QueryExecutor.execute(QueryExecutor.java:117)
        at org.apache.tajo.master.GlobalEngine.executeQuery(GlobalEngine.java:191)
        at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.submitQuery(TajoMasterClientService.java:303)
        at org.apache.tajo.ipc.TajoMasterClientProtocol$TajoMasterClientProtocolService$2.callBlockingMethod(TajoMasterClientProtocol.java:675)
        at org.apache.tajo.rpc.BlockingRpcServer$ServerHandler.channelRead0(BlockingRpcServer.java:100)
        at org.apache.tajo.rpc.BlockingRpcServer$ServerHandler.channelRead0(BlockingRpcServer.java:61)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at org.apache.tajo.rpc.MonitorServerHandler.channelRead(MonitorServerHandler.java:70)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jinossy** [comment]
@jihoonson 
Thanks for your review! 
I've update the patch. Could you review again?

**Comment by jihoonson** [comment]
+1 ship it!

**Pull request closed without merging**
