### PR TITLE
TAJO-1649 Change Rest API /databases/{database-name}/functions to /functions

### PR DESCRIPTION
**Pull request by charsyam**
functions is not related with database.
so GET /functions is more clear.

### CODE REVIEW

**Comment by hyunsik** [comment]
+1
The patch looks good to me.

**Comment by hyunsik** [comment]
Could you update the specification on the wiki too?

**Comment by hyunsik** [comment]
I just committed the patch to master branch. I missed to add 'close command' in the commit log. Could you close this ticket?

**Comment by charsyam** [comment]
I updated wiki

**Pull request closed without merging**
