### PR TITLE
TAJO-1495: Clean up CatalogStore

### PR DESCRIPTION
**Pull request by blrunner**

### CODE REVIEW

**Comment by blrunner** [comment]
For the reference, I finished this successfully on MySQL, MariaDB, PostgreSQL.

**Comment by jinossy** [comment]
@ykrips
Could you review this PR ?

**Comment by ykrips** [comment]
@jinnosy.
Sure. no problems. However, I don't have much knowledge on mysql and mariadb, and need lead time to make over for these dbms. If it is not an urgent issue, could you wait for some time to recover my knowledge on mysql and mariadb?

**Comment by jinossy** [comment]
Yes, I can. This PR is not an urgent issue. please go ahead
Thank you!!

**Comment by blrunner** [comment]
Thanks @ykrips and @jinossy  :)

**Comment by ykrips** [comment]
@blrunner ,
Column size of `VALUE_` on `OPTIONS` table has been increased to 4000 bytes, could you change these size in your patch? Patch for TAJO-1360 already uploaded earlier, so I feel that it could be better to apply first to our master branch.

**Comment by blrunner** [comment]
@ykrips 

Thanks for your comments. I've just updated it. :)

**Comment by ykrips** [comment]
+1
TestCatalog testcase has passed on my derby, mysql, mariadb, postgresql, and oracle database. Also, table schema verified by using its own command-line commands.

**Comment by blrunner** [comment]
@ykrips 

Thanks for your kind and quick review. :)
I'll ship it now.

**Pull request closed without merging**
