### PR TITLE
TAJO-1400: Add TajoStatement::setMaxRows method support

### PR DESCRIPTION
**Pull request by hys9958**
I implemented the setMaxRows and getMaxRows method support.
Please review my patch.

thanks.

### CODE REVIEW

**Comment by blrunner** [comment]
Thank you for your contribution.
I'll review the patch today. :)

**Comment by jihoonson** [comment]
Would you add some unit tests?
TestTajoJDBC will be good to add tests.

**Comment by hys9958** [comment]
Ok, jihoonson,
I'll update the TestTajoJDBC for unit tests of this issue soon.

**Comment by jihoonson** [comment]
+1
Thanks for your contribution!

**Comment by jinossy** [comment]
@hys9958 
How do you think that move the setMaxRows() to TajoStatement ?

**Comment by jihoonson** [comment]
@jinossy thanks for the good suggestion.
It would be a better implementation.

**Comment by hys9958** [comment]
@jinossy Ok, It's better idea.
I'll re-patch the implementation of maxRows(). :)

**Comment by jihoonson** [comment]
@hys9958 thanks. I'll wait for the next patch.

**Comment by hys9958** [comment]
Hi @jihoonson ,
Query return value is 'java.sql.ResultSet' interfase in TajoStatement. It need to many refactoring.
And i'll also another patch about getMoreResults. When the getMoreResults patch time, i update maxRows.

**Comment by jihoonson** [comment]
Ok. Here is my +1.
If there are no objections, I'll commit.

**Pull request closed without merging**
