### PR TITLE
TAJO-1488: Implement KafkaTablespace

### PR DESCRIPTION
**Pull request by combineads**
KafkaTablespace provides the split information, this is KafkaFragment, using getSplits.
The issue is related to TAJO-1487. So first, must be commit TAJO-1487.

### CODE REVIEW

**Comment by combineads** [comment]
I will modify the hBaseTablespace variable name to kafkaTablespace in TestKafkaTablespace.java.

**Comment by jinossy** [comment]
@combineads Hi Thanks for your contirbution!
Could you fix broken build ?

**Comment by combineads** [comment]
@jinossy Thanks for your review.
I solved the error to add the kafka storage in the pom.xml of tajo-storage.

**Comment by jinossy** [comment]
Thanks for your quick fix. I'll review soon.

**Comment by jinossy** [comment]
rebase please

**Comment by combineads** [comment]
@jinossy Done rebase.
Thanks for your reviews.

**Comment by jinossy** [comment]
+1 travis failure is not related this PR. 
I was create to https://issues.apache.org/jira/browse/TAJO-1635
Thank you for your contribution!!

**Pull request closed without merging**
