### PR TITLE
TAJO-1442: Improve Hive Compatibility

### PR DESCRIPTION
**Pull request by blrunner**
I refactored HCatalogStore to HiveCatalogStore. And I added more hive profiles as follows: hive 0.14.0, hive 1.0.0, hive 1.1.0.

### CODE REVIEW

**Comment by blrunner** [comment]
I removed old hive profiles. Because I had already removed hcatalog dependencies. 
For the reference, I found that Tajo had run successfully with hive, such as, hive-0.13.1, hive-0.14.0, hive-1.0.0, hive-1.1.0.

**Comment by blrunner** [comment]
Rebasing commits against the master branch. :)

**Comment by jihoonson** [comment]
Hi @blrunner.
With my laptop, ```mvn clean install -Pparallel-test -DLOG_LEVEL=WARN -Dmaven.fork.count=2``` is failed due to missing licences while testing on ```Tajo Catalog Drivers```. This seems due to some generated files. 
In addition, I found that the test time on ```Tajo Core``` is significantly increased from 13:58 min to 53:34 min.
Would you check it?

**Comment by blrunner** [comment]
@jihoonson 

Thank you for your review. I'll check it soon.:)

**Comment by blrunner** [comment]
@jihoonson 

The time delay was caused by source sync. After rebasing to the master branch, the build time took as follows.

1. Apply TAJO-1442 patch
- Total time: 19:13 min

2. Apache Trunk code
- Total time: 19:58 min

**Comment by jihoonson** [comment]
+1
It seems that there are some problems in my machine. Thanks!

**Comment by blrunner** [comment]
Thanks @jihoonson 

I'll commit this soon. :)

**Pull request closed without merging**
