### PR TITLE
TAJO-1479: NPE during startup CatalogStore

### PR DESCRIPTION
**Pull request by blrunner**
I succeed to startup MySQLStore on my local cluster. For the reference, I fixed some typos about partition tables.

### CODE REVIEW

**Comment by jihoonson** [comment]
+1
ship it!

**Comment by blrunner** [comment]
Thanks @jihoonson 

I'll ship it soon. :)

**Comment by blrunner** [comment]
@jihoonson 

I've just fixed other typos for postgresql.
Could you check it again?

**Comment by jihoonson** [comment]
+1
The patch LGTM.

**Pull request closed without merging**
