### PR TITLE
TAJO-1707: Rack local count can be more than actual number of tasks.

### PR DESCRIPTION
**Pull request by jinossy**

### CODE REVIEW

**Comment by jinossy** [comment]
I've remove the cancellation count

**Comment by jihoonson** [comment]
This patch looks good, but totalAssigned is the sum of only hostLocalAssigned and rackLocalAssigned. How about adding a new variable to keep the total number of attempts including cancelled attempts?

**Comment by jinossy** [comment]
Good idea. I'm going to add totalAttempts

**Comment by jihoonson** [comment]
+1 LGTM!

**Pull request closed without merging**
