### PR TITLE
TAJO-2126: Allow parallel execution of non-leaf sibling ExecutionBlocks

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by hyunsik** [comment]
The change looks straightforward and reasonable. But, I'm concerned with potential side effects. Did you do enough tests in cluster environments?

**Comment by jihoonson** [comment]
I did basic tests to verify query results, but there is one thing I'm concerned with. That is the shuffle cost. This patch enables the parallel execution of non-leaf EBs, thereby more shuffle operations can be executed simultaneously. It can increase the shuffle cost especially for range shuffle due to heavy index search.
So, we need to improve hash shuffle by reusing http connections and range shuffle by redesigning the index structure.

However, I think the heavy shuffle costs should be addressed in other Jiras. What do you think?

**Comment by hyunsik** [comment]
Do you mean more shuffle cost caused by heavy load?

**Comment by jihoonson** [comment]
It is possible in single query execution. If multiple queries are executed, the shuffle cost of the current implementation will also be huge.

**Comment by hyunsik** [comment]
Yep, I agree. I think that this patch will enhance the machine resource utilization instead of causing more shuffle cost.

+1 LGTM

**Comment by jihoonson** [comment]
Thanks for your review!

**Pull request closed without merging**
