### PR TITLE
TAJO-1775: HCatalogStore need to be deprecated.

### PR DESCRIPTION
**Pull request by blrunner**
If old version users use tajo 0.11.0 using existing hcatalog configuration, they will fail to run TajoMaster with ClassNotFoundException. So, we need to deprecate HCatalogStore.

### CODE REVIEW

**Comment by hyunsik** [comment]
I think that the unit test seems to be not necessary because it is striaghtforward.

**Comment by blrunner** [comment]
Thanks @hyunsik 
I've removed it. :-)

**Comment by jihoonson** [comment]
Looks good to me.

**Comment by hyunsik** [comment]
+1

**Pull request closed without merging**
