### PR TITLE
TAJO-1382 Refactoring of NumberUtil to keep single copy of codes both for byte[] and bytebuf

### PR DESCRIPTION
**Pull request by navis**
Introduced value accessor to consolidate two pair of codes

### CODE REVIEW

**Comment by jinossy** [comment]
Thank you for your contribution, I ran integer benchmark. but I found performance decrement about 10%
I will upload the benchmark patch to jira. Can you check this ? 

* Original
```
Result: 25611504.825 ±(99.9%) 126889.037 ops/s [Average]
  Statistics: (min, avg, max) = (25290299.861, 25611504.825, 25869540.937), stdev = 169393.233
  Confidence interval (99.9%): [25484615.788, 25738393.861]

# Run complete. Total time: 00:01:02

Benchmark                                      Mode  Cnt         Score        Error  Units
BenchmarkNumberUtil.parseIntThroughput        thrpt   25  29012506.326 ± 246843.623  ops/s
BenchmarkNumberUtil.unsafeParseIntThroughput  thrpt   25  25611504.825 ± 126889.037  ops/s
```

* Applied your patch
```
Result: 22658219.224 ±(99.9%) 190563.440 ops/s [Average]
  Statistics: (min, avg, max) = (22138484.562, 22658219.224, 23075760.439), stdev = 254396.740
  Confidence interval (99.9%): [22467655.784, 22848782.663]

# Run complete. Total time: 00:01:02

Benchmark                                      Mode  Cnt         Score        Error  Units
BenchmarkNumberUtil.parseIntThroughput        thrpt   25  23777917.323 ± 157067.557  ops/s
BenchmarkNumberUtil.unsafeParseIntThroughput  thrpt   25  22658219.224 ± 190563.440  ops/s
```

**Comment by navis** [comment]
It is some difference. Then, we can discard this patch.

**Comment by navis** [comment]
Anyway, cannot reproduce test fail.

**Comment by jinossy** [comment]
Guys, Any idea? If you have no idea, I will discard this patch

**Comment by jinossy** [comment]
@navis 
Could you close PR and jira issue ?

**Pull request closed without merging**
