### PR TITLE
TAJO-1713: Change the type of edge cache in JoinGraphContext from HashMap to LRUMap

### PR DESCRIPTION
**Pull request by jihoonson**
I've also cleared variables which are unnecessary after join optimization.

[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/654)

### CODE REVIEW

**Comment by hyunsik** [comment]
LRUMap has different initial sizes according to whether it is used in tests or not. Is it necessary or is it enough for tests?

**Comment by jihoonson** [comment]
It is enough for tests. According to my experience, the cache size is increased up to about 120 entries while inner joining 5 tables. So, I think it is enough to set the max cache size as 100 during tests.

**Comment by jihoonson** [comment]
I've removed the codes for adjusting map size during tests because the overhead of map size seems not significant.

**Comment by hyunsik** [comment]
LGTM! +1

**Comment by jihoonson** [comment]
Thanks for the review!

**Pull request closed without merging**
