### PR TITLE
TAJO-1704: Apply ComparableTuple to *AggregateExec.

### PR DESCRIPTION
**Pull request by hyunsik**
[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/650)

### CODE REVIEW

**Comment by hyunsik** [comment]
Just rebased.

**Comment by blrunner** [comment]
+1

LGTM! :-)

**Comment by blrunner** [comment]
Hi @hyunsik 

Could you explain why you changed queries and results for window function test?

**Comment by jihoonson** [comment]
@hyunsik are you working on this issue? If not, please close this PR. We can open again when we need later.

**Comment by hyunsik** [comment]
closed. Thank you.

**Pull request closed without merging**
