### PR TITLE
TAJO-1428: Support min, max builtin functions for DATE, TIME, TIMESTAMP

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by sirpkt** [comment]
Hi, @dongjoon-hyun,
Patch is straightforward and looks good.
However, how about add some unit test code for new functions?

**Comment by dongjoon-hyun** [comment]
Thank you, @sirpkt . I will soon.

**Comment by dongjoon-hyun** [comment]
Hi, @sirpkt . I added unit test. Also, I rebased and tested.

**Comment by sirpkt** [comment]
It looks good and consistent with min, max functions of other types, @dongjoon-hyun.

However, I'll post +1 after it passes Travis CI.

**Comment by dongjoon-hyun** [comment]
Thank you for your fast and thorough review, @sirpkt .

**Comment by dongjoon-hyun** [comment]
Hi, @sirpkt . It passes Travis CI. Could you commit this patch, please?

**Comment by sirpkt** [comment]
+1

I'll commit the patch

**Comment by dongjoon-hyun** [comment]
Thank you for spending your time here, @sirpkt . I know you're very busy for developing your issues. :)

**Pull request closed without merging**
