### PR TITLE
TAJO-1599: Implement NodeResourceManager and Status updater

### PR DESCRIPTION
**Pull request by jinossy**

### CODE REVIEW

**Comment by jihoonson** [comment]
Hi @jinossy, it's really nice work. 
I've almost read your patch. I'll finish my review soon.

**Comment by jihoonson** [comment]
+1 LGTM!

**Comment by jinossy** [comment]
Thank you for the review!
I'll commit soon

**Comment by hyunsik** [comment]
This patch requires updating documentation because it affects the resource configuration.

**Comment by jinossy** [comment]
I was add the new key of disk configuration because if I change the configuration, it affects the current resource. 
When I remove the legacy configuration, I will update the document.

**Pull request closed without merging**
