### PR TITLE
TAJO-1921: Hbase Storage can cause NPE when the hbase cluster is restarted

### PR DESCRIPTION
**Pull request by combineads**
It was similarly modified by referring to TableInputFormatBase#getSplits(JobContext). Cause as much as possible to follow a policy of HBase.
And then the size of memstore will not have a big impact for bigdata analysis. So it was removed.

### CODE REVIEW

**Comment by combineads** [comment]
@hyunsik I think TAJO-1921 and TAJO-1940 seems to be a conflict. If TAJO-1940 is deployed, I can also be modified again.
Thanks.

**Comment by hyunsik** [comment]
I'm reviewing the patch. Your suggestion sounds good to me.

**Comment by hyunsik** [comment]
The patch looks good to me. Here are some comments.

Our coding standard uses 2 space instead of tab. Some lines do not follow the indent of our coding standard.  Please refer to https://cwiki.apache.org/confluence/display/TAJO/Code+Style.

Other parts looks good to me. Here is my +1. Could you correct line indents? Then, I'll commit it soon.

**Comment by combineads** [comment]
I had to modify the source.
Thank you for comment.

**Comment by combineads** [comment]
@hyunsik Anything else to commit this PR?

**Comment by hyunsik** [comment]
+1 the patch looks good to me. I'm sorry for late.

**Pull request closed without merging**
