### PR TITLE
TAJO-1827: JSON parsing error at storage-site.json while tajo master starts up

### PR DESCRIPTION
**Pull request by blrunner**
Removed comments in the template file.

### CODE REVIEW

**Comment by hyunsik** [comment]
How about removing all contents from the template file? The default template will add a tablespace as soon as a user just copies ``storage-site.json`` from ``storage-site.json.template``. It may cause some problem.

**Comment by blrunner** [comment]
Thanks @hyunsik .
I've reflected your comments.

**Comment by hyunsik** [comment]
+1
The patch looks good to me.

**Comment by blrunner** [comment]
Thanks @hyunsik 

I added a description element to JSON template instead of removing contents. If possible, could you check it again?

**Comment by blrunner** [comment]
@hyunsik 

On second thought, the template file might cause a problem when starting HBaseTableSpace. I'll shit previous version. :)

**Comment by hyunsik** [comment]
+1
Ship it. the patch looks good to me.

**Pull request closed without merging**
