### PR TITLE
TAJO-1360: VALUES_ field in OPTIONS table of catalog store should be longer. 

### PR DESCRIPTION
**Pull request by charsyam**
I suggest OPTIONS size as 4000, because max size of oracle varchar2 is just 4000
I researched docs for these patch.

maria: https://mariadb.com/kb/en/mariadb/varchar/
mysql: http://dev.mysql.com/doc/refman/5.7/en/char.html
postgres: http://www.postgresql.org/docs/8.3/static/datatype-character.html
derby: https://db.apache.org/derby/docs/10.7/ref/rrefsqlj41207.html
oracle: https://docs.oracle.com/cd/B28359_01/server.111/b28320/limits001.htm#i287903
(here varchar2 limit is just 4000)

### CODE REVIEW

**Comment by charsyam** [comment]
@hyunsik @dongjoon-hyun @ykrips 
I'm sorry to make you confused. Thank you.

**Comment by ykrips** [comment]
@hyunsik ,
If you are unable to work on this pull request, can I finish up this request?
This issue is related to another pull request, #491 .

**Comment by hyunsik** [comment]
@ykrips I would greatly appreciate it if you finish up this request.

**Comment by ykrips** [comment]
Hello All,
+1
This patch was tested with Derby, MySQL 5.1.17, MariaDB 10.0.17, PostgreSQL 8.4.18, and Oracle 12.1.0.2.0, and worked well as expected. I will commit it in a short time.

**Pull request closed without merging**
