### PR TITLE
TAJO-2115: Change the size of the VALUE_ column in OPTIONS table

### PR DESCRIPTION
**Pull request by blrunner**
This patch just updates the ``VALUE_`` column size of ``OPTIONS`` table. Existing codes of catalog module have remained static. Here are corrections as following:

DBMS | Existing Type | Updated Type 
-------------------|----------------------|--------------------------
Derby | VARCHAR(4000) | LONG VARCHAR  
MySQL | VARCHAR(4000) | TEXT
MariaDB | VARCHAR(4000) | TEXT 
PostgreSQL | VARCHAR(4000) | TEXT
Oracle | VARCHAR2(4000) | LONG
 
I referenced following sites.
* https://db.apache.org/derby/docs/10.1/ref/rrefsqlj15147.html
* https://docs.oracle.com/cd/B19306_01/java.102/b14188/datamap.htm
* https://en.wikibooks.org/wiki/Converting_MySQL_to_PostgreSQL

### CODE REVIEW

**Comment by hyunsik** [comment]
Could you rebase it?

**Comment by jihoonson** [comment]
This is a temporal solution. We need to investigate a better way.

**Comment by blrunner** [comment]
Rebased.

**Comment by hyunsik** [comment]
@jihoonson In this issue or in another issue?

@blrunner It seems to need rebase again.

**Comment by jihoonson** [comment]
I mean, this issue is not addressing the fundamental problem. I believe that we need to devise a better way to map Tajo columns and HBase columns.

**Comment by blrunner** [comment]
This patch is a temporary solution. We need to solve the fundamental problem about this issue.

**Pull request closed without merging**
