### PR TITLE
TAJO-1314: Documentation for the support of the swift

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by hyunsik** [comment]
Could you add some example for CREATE TABLE? It may be similar to those of other storage types. Nevertheless, the example would be helpful to users.

**Comment by jihoonson** [comment]
Sure. I'll add it.

**Comment by jihoonson** [comment]
Added an example of the table creation.

**Comment by hyunsik** [comment]
+1
The patch looks great to me. Ship it!

**Pull request closed without merging**
