### PR TITLE
TAJO-2168: NullPointerException occurs when a simple query contains a…

### PR DESCRIPTION
**Pull request by jihoonson**
… python udf.

### CODE REVIEW

**Comment by jihoonson** [comment]
Fixed test failure.

**Comment by jihoonson** [comment]
I additionally ArrayOutOfBoundsException which occurs while loading python functions. Our parser used for loading python functions is very naive, so it cannot parse complex functions. However, during unit testing, our python codes like controller.py are unexpectedly loaded, which causes ArrayOutOfBoundsException. So I changed the directory name for python functions.

**Comment by jinossy** [comment]
+1 LGTM!
Ship it!

**Comment by jihoonson** [comment]
Thank you for your review.

**Pull request closed without merging**
