### PR TITLE
TAJO-1844: Eliminate explicit diamond expressions

### PR DESCRIPTION
**Pull request by dkhwangbo**
Eliminate explicit diamond expressions in whole project.

### CODE REVIEW

**Comment by hyunsik** [comment]
+1 LGTM

**Comment by hyunsik** [comment]
Could you close this issue? I missed to add the close command to the commit log.
https://git-wip-us.apache.org/repos/asf?p=tajo.git;a=commit;h=aa699c70943f7563e77f5828683cd0399998a0f9

**Comment by dkhwangbo** [comment]
I find some expression was remained till now. so remove again.
I really sorry about your inconvenient caused by my mistake.

**Comment by jihoonson** [comment]
This ticket is already committed, so you should make another ticket on Jira for remaining issues.

**Comment by dkhwangbo** [comment]
@jihoonson Thanks for your reply. I'll do that.

**Pull request closed without merging**
