### PR TITLE
TAJO-1737: Implement SQL Parser rule for Map type.

### PR DESCRIPTION
**Pull request by hyunsik**
[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/675)

### CODE REVIEW

**Comment by hyunsik** [comment]
I fixed failed unit tests and rebased.

**Comment by jihoonson** [comment]
This patch looks good in overall. However, it would be better if querying on map columns is not allowed.

**Comment by hyunsik** [comment]
Do you mean the table creation with map type?

**Comment by hyunsik** [comment]
I just rebased and reflected the comments.

**Comment by hyunsik** [comment]
rebased.

**Comment by hyunsik** [comment]
rebased

**Comment by jihoonson** [comment]
+1 ship it!

**Pull request closed without merging**
