### PR TITLE
TAJO-1663: Change the variable name storeType to dataFormat.

### PR DESCRIPTION
**Pull request by hyunsik**

### CODE REVIEW

**Comment by blrunner** [comment]
Hi @hyunsik 

When I tested a simple query using your patch, the query failed as following:

```
2015-09-27 16:22:49,697 INFO org.apache.tajo.master.GlobalEngine: Query: select * from lineitem limit 10
2015-09-27 16:22:49,901 ERROR org.apache.tajo.catalog.CatalogServer: 
Stack Trace:
org.apache.tajo.exception.TajoInternalError: internal error: Unknown column 'DATA_FORMAT' in 'field list'
	at org.apache.tajo.catalog.store.AbstractDBStore.getTable(AbstractDBStore.java:1798)
	at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.getTableDesc(CatalogServer.java:611)
	at org.apache.tajo.catalog.AbstractCatalogClient.getTableDesc(AbstractCatalogClient.java:274)
	at org.apache.tajo.catalog.AbstractCatalogClient.getTableDesc(AbstractCatalogClient.java:288)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitRelation(BaseSchemaBuildPhase.java:415)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitRelation(BaseSchemaBuildPhase.java:74)
	at org.apache.tajo.plan.algebra.BaseAlgebraVisitor.visit(BaseAlgebraVisitor.java:99)
	at org.apache.tajo.plan.algebra.BaseAlgebraVisitor.visitRelationList(BaseAlgebraVisitor.java:429)
	at org.apache.tajo.plan.algebra.BaseAlgebraVisitor.visit(BaseAlgebraVisitor.java:96)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitLimit(BaseSchemaBuildPhase.java:277)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitLimit(BaseSchemaBuildPhase.java:74)
	at org.apache.tajo.plan.algebra.BaseAlgebraVisitor.visit(BaseAlgebraVisitor.java:63)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitProjection(BaseSchemaBuildPhase.java:220)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase$Processor.visitProjection(BaseSchemaBuildPhase.java:74)
	at org.apache.tajo.plan.algebra.BaseAlgebraVisitor.visit(BaseAlgebraVisitor.java:60)
	at org.apache.tajo.plan.rewrite.BaseSchemaBuildPhase.process(BaseSchemaBuildPhase.java:71)
	at org.apache.tajo.plan.rewrite.BaseLogicalPlanPreprocessEngine.process(BaseLogicalPlanPreprocessEngine.java:94)
	at org.apache.tajo.plan.LogicalPlanPreprocessor.process(LogicalPlanPreprocessor.java:43)
	at org.apache.tajo.plan.LogicalPlanner.createPlan(LogicalPlanner.java:164)
	at org.apache.tajo.plan.LogicalPlanner.createPlan(LogicalPlanner.java:154)
	at org.apache.tajo.master.GlobalEngine.createLogicalPlan(GlobalEngine.java:274)
```

Could you check it?

**Comment by hyunsik** [comment]
@blrunner You need to upgrade the catalog. I missed to bump up the catalog version.

**Comment by jihoonson** [comment]
+1 looks good to me.
Please update the catalog version before you commit.

**Comment by hyunsik** [comment]
Thank you. I'll commit it soon.

**Pull request closed without merging**
