### PR TITLE
TAJO-1542: Refactoring of HashJoinExecs.

### PR DESCRIPTION
**Pull request by hyunsik**
See this pull request.
https://github.com/apache/tajo/pull/529

[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/567)

### CODE REVIEW

**Comment by hyunsik** [comment]
@jihoonson You recently refactored some join algorithms. So, I think that it would be great if you review this patch too.

**Comment by jihoonson** [comment]
@hyunsik sorry for late response. I'm reviewing your patch, and will finish asap.

**Comment by jihoonson** [comment]
<sup>**[tajo-common/src/main/java/org/apache/tajo/storage/NullTuple.java, line 28 \[r2\]](https://reviewable.io:443/reviews/apache/tajo/567#-JpGTPiOHTlpLVMLBGBA)** ([raw file](https://github.com/apache/tajo/blob/0554f9f8a10f9720e5c6e5da26183b7d37d34cf3/tajo-common/src/main/java/org/apache/tajo/storage/NullTuple.java#L28)):</sup>
Very nice.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/apache/tajo/567)

**Comment by jihoonson** [comment]
<sup>**[tajo-catalog/tajo-catalog-common/src/main/java/org/apache/tajo/catalog/Schema.java, line 496 \[r2\]](https://reviewable.io:443/reviews/apache/tajo/567#-JpGtvvX0rsY9XvdaCKx)** ([raw file](https://github.com/apache/tajo/blob/0554f9f8a10f9720e5c6e5da26183b7d37d34cf3/tajo-catalog/tajo-catalog-common/src/main/java/org/apache/tajo/catalog/Schema.java#L496)):</sup>
This line looks hard-coded.
Would you explain your intention?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/apache/tajo/567)

**Comment by jihoonson** [comment]
+1. This patch looks good to me.
I left only one trivial comment.
Thanks for your work.

**Pull request closed without merging**
