### PR TITLE
TAJO-1329: Improve Schema class to support nested struct support.

### PR DESCRIPTION
**Pull request by hyunsik**

### CODE REVIEW

**Comment by hyunsik** [comment]
I've updated the patch as follows:
 * Change protobuf fields.
 * Add more comments.
 * Clean up some methods.

**Comment by jihoonson** [comment]
@hyunsik, thanks for your work.
With this patch, it seems that users can execute ```CREATE TABLE``` statements with nested schemas.
So, I simply submitted an example query used in a junit test, but found the following error:
```
default> create table nested_table (f1 int, nested_field record (f2 int4, f3 int8), f3 text);
ERROR: Cannot create table "default.nested_table".
```
The error message is follows:
```
2015-03-01 22:04:22,658 ERROR org.apache.tajo.catalog.CatalogServer: java.sql.BatchUpdateException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
org.apache.tajo.catalog.exception.CatalogException: java.sql.BatchUpdateException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
        at org.apache.tajo.catalog.store.AbstractDBStore.createTable(AbstractDBStore.java:892)
        at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.createTable(CatalogServer.java:604)
        at org.apache.tajo.catalog.AbstractCatalogClient$23.call(AbstractCatalogClient.java:481)
        at org.apache.tajo.catalog.AbstractCatalogClient$23.call(AbstractCatalogClient.java:478)
        at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:94)
        at org.apache.tajo.catalog.AbstractCatalogClient.createTable(AbstractCatalogClient.java:478)
        at org.apache.tajo.master.exec.DDLExecutor.createTable(DDLExecutor.java:248)
        at org.apache.tajo.master.exec.DDLExecutor.createTable(DDLExecutor.java:208)
        at org.apache.tajo.master.exec.DDLExecutor.execute(DDLExecutor.java:88)
        at org.apache.tajo.master.exec.QueryExecutor.execute(QueryExecutor.java:98)
        at org.apache.tajo.master.GlobalEngine.executeQuery(GlobalEngine.java:163)
        at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.submitQuery(TajoMasterClientService.java:287)
        at org.apache.tajo.ipc.TajoMasterClientProtocol$TajoMasterClientProtocolService$2.callBlockingMethod(TajoMasterClientProtocol.java:543)
        at org.apache.tajo.rpc.BlockingRpcServer$ServerHandler.messageReceived(BlockingRpcServer.java:103)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.BatchUpdateException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
        at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
        at org.apache.tajo.catalog.store.AbstractDBStore.createTable(AbstractDBStore.java:828)
        ... 39 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeBatchElement(Unknown Source)
        ... 41 more
Caused by: java.sql.SQLException: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
        ... 49 more
Caused by: ERROR 23505: The statement was aborted because it would have caused a duplicate key value in a unique or primary key constraint or unique index identified by 'COLUMNS_PK' defined on 'COLUMNS'.
        at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexChanger.insertAndCheckDups(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexChanger.doInsert(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexChanger.insert(Unknown Source)
        at org.apache.derby.impl.sql.execute.IndexSetChanger.insert(Unknown Source)
        at org.apache.derby.impl.sql.execute.RowChangerImpl.insertRow(Unknown Source)
        at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
        at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
        at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
        at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
        ... 43 more
```

**Comment by hyunsik** [comment]
Hi @jihoonson,

I've updated the patch to allow duplicated names in different nested levels. I changed the primary key in catalog stores to TID and ORDINAL_POSITION instead of TID and COLUMN_NAME. Even though DB catalog itself does not guarantee the uniqueness of column names in the same level, the uniqueness is guaranteed by Schema. So, it would be Ok.

**Comment by jihoonson** [comment]
@hyunsik with the latest patch, the ```create table``` statement works well.
However, I couldn't see the detailed information of nested columns. Please see the following example.
```
default> create table nested_table (f1 int, nested_field record (f2 int4, f3 int8), f3 text);
OK
default> \d
nested_table
default> \d nested_table

table name: default.nested_table
table path: hdfs://localhost:7020/tajo/warehouse/default/nested_table
store type: CSV
number of rows: 0
volume: 0 B
Options: 
	'text.delimiter'='|'

schema: 
f1	INT4
nested_field	RECORD
f3	TEXT
```
The ```nested_field``` column is presented as just one record, and details are veiled. It would be much greater if you improve it.

**Comment by hyunsik** [comment]
I rebased it. Also, this patch additionally includes the following changes:
 * Improved tajo-dump to dump nested schema
 * enabled \d command in tsql to show nested schema correctly.

**Comment by jihoonson** [comment]
@hyunsik sorry to say, but would you please check this error again?
```
default> create table nested_table2 (f1 int, nf1 record (f1 int4, f3 double), nf2 record (f1 int4, nf1 record (f1 int4, f2 text), nf2 record (f1 int4, f2 text), f2 double), f2 text);
OK
default> \d
nested_table
nested_table2
default> \d nested_table2
ERROR: org.apache.tajo.rpc.TajoServiceException: java.lang.NullPointerException
com.google.protobuf.ServiceException: org.apache.tajo.rpc.TajoServiceException: java.lang.NullPointerException
	at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:104)
	at org.apache.tajo.client.CatalogAdminClientImpl.getTableDesc(CatalogAdminClientImpl.java:216)
	at org.apache.tajo.client.TajoClientImpl.getTableDesc(TajoClientImpl.java:217)
	at org.apache.tajo.cli.tsql.commands.DescTableCommand.invoke(DescTableCommand.java:50)
	at org.apache.tajo.cli.tsql.TajoCli.executeMetaCommand(TajoCli.java:471)
	at org.apache.tajo.cli.tsql.TajoCli.executeParsedResults(TajoCli.java:445)
	at org.apache.tajo.cli.tsql.TajoCli.runShell(TajoCli.java:419)
	at org.apache.tajo.cli.tsql.TajoCli.main(TajoCli.java:694)
Caused by: org.apache.tajo.rpc.TajoServiceException: java.lang.NullPointerException
	at org.apache.tajo.rpc.BlockingRpcClient.makeTajoServiceException(BlockingRpcClient.java:188)
	at org.apache.tajo.rpc.BlockingRpcClient.access$500(BlockingRpcClient.java:42)
	at org.apache.tajo.rpc.BlockingRpcClient$ClientChannelInboundHandler.channelRead(BlockingRpcClient.java:211)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.ServiceException: com.google.protobuf.ServiceException: java.lang.NullPointerException
	at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.getTableDesc(TajoMasterClientService.java:816)
	at org.apache.tajo.ipc.TajoMasterClientProtocol$TajoMasterClientProtocolService$2.callBlockingMethod(TajoMasterClientProtocol.java:585)
	at org.apache.tajo.rpc.BlockingRpcServer$ServerHandler.channelRead(BlockingRpcServer.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.getTableDesc(TajoMasterClientService.java:805)
	... 18 more

	... 17 more
```
The main reason looks duplicated names. Here is the master log.
```
2015-03-12 20:33:05,241 INFO org.apache.tajo.master.exec.DDLExecutor: Table default.nested_table2 is created (0)
2015-03-12 20:33:08,601 ERROR org.apache.tajo.catalog.Schema: Already exists column nf1
2015-03-12 20:33:08,601 ERROR org.apache.tajo.catalog.CatalogServer: org.apache.tajo.catalog.exception.AlreadyExistsFieldException: Already Exists Field: nf1
2015-03-12 20:33:08,602 ERROR org.apache.tajo.catalog.AbstractCatalogClient: com.google.protobuf.ServiceException: org.apache.tajo.catalog.exception.AlreadyExistsFieldException: Already Exists Field: nf1
com.google.protobuf.ServiceException: com.google.protobuf.ServiceException: org.apache.tajo.catalog.exception.AlreadyExistsFieldException: Already Exists Field: nf1
        at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:104)
        at org.apache.tajo.catalog.AbstractCatalogClient.getTableDesc(AbstractCatalogClient.java:280)
        at org.apache.tajo.master.TajoMasterClientService$TajoMasterClientProtocolServiceHandler.getTableDesc(TajoMasterClientService.java:805)
        at org.apache.tajo.ipc.TajoMasterClientProtocol$TajoMasterClientProtocolService$2.callBlockingMethod(TajoMasterClientProtocol.java:585)
        at org.apache.tajo.rpc.BlockingRpcServer$ServerHandler.channelRead(BlockingRpcServer.java:113)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.ServiceException: org.apache.tajo.catalog.exception.AlreadyExistsFieldException: Already Exists Field: nf1
        at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.getTableDesc(CatalogServer.java:537)
        at org.apache.tajo.catalog.AbstractCatalogClient$13.call(AbstractCatalogClient.java:287)
        at org.apache.tajo.catalog.AbstractCatalogClient$13.call(AbstractCatalogClient.java:280)
        at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:94)
        ... 20 more
Caused by: org.apache.tajo.catalog.exception.AlreadyExistsFieldException: Already Exists Field: nf1
        at org.apache.tajo.catalog.Schema.addColumn(Schema.java:315)
        at org.apache.tajo.catalog.Schema.addColumn(Schema.java:344)
        at org.apache.tajo.catalog.Schema.<init>(Schema.java:118)
        at org.apache.tajo.catalog.Schema.deserializeColumn(Schema.java:92)
        at org.apache.tajo.catalog.Schema.<init>(Schema.java:62)
        at org.apache.tajo.catalog.CatalogUtil.getQualfiedSchema(CatalogUtil.java:329)
        at org.apache.tajo.catalog.store.AbstractDBStore.getTable(AbstractDBStore.java:1421)
        at org.apache.tajo.catalog.CatalogServer$CatalogProtocolHandler.getTableDesc(CatalogServer.java:528)
        ... 23 more
```

**Pull request closed without merging**
