### PR TITLE
TAJO-1434: Fix supporting version of Hadoop

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by dongjoon-hyun** [comment]
According to the discussion in https://issues.apache.org/jira/browse/TAJO-1434, pom.xml is updated also.

**Comment by jinossy** [comment]
+1 LGTM
I'll commit it soon

**Comment by dongjoon-hyun** [comment]
@jinossy Thank you very much!

**Pull request closed without merging**
