### PR TITLE
TAJO-1889: UndefinedColumnException when a query with table subquery is executed on self-describing tables

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by hyunsik** [comment]
+1
The patch looks good to me. The test looks failed, but it is not related to this patch.

**Comment by jihoonson** [comment]
@hyunsik, thank you for your quick review, but I updated my patch to fix one more problem.
Would you please review again?

**Comment by jihoonson** [comment]
I also put my patch on jira to trigger jenkins.

**Comment by jihoonson** [comment]
I don't know why the diff includes the changes other than I modified.
I'll close and reopen this pr.

**Pull request closed without merging**
