### PR TITLE
TAJO-1160: Remove Hadoop dependency from tajo-client module.

### PR DESCRIPTION
**Pull request by jinossy**
I’ve refer to the thinClient of hyunsik repo

### CODE REVIEW

**Comment by blrunner** [comment]
Hi @jinossy 

Thanks for your works.
But I found a build failure as follows:
{code:xml}
Results :

Tests in error: 
  TestTajoClient.testGetQueryStatusAndResultAfterFinish:644 » Service org.apache...
  TestTajoClient.testGetFinishedQueryList:617 » Service org.apache.tajo.rpc.Tajo...

Tests run: 1361, Failures: 0, Errors: 2, Skipped: 0
{code}

Could you check it again?

**Comment by jinossy** [comment]
Thank you for the review
A simple query are not to allocate a query master. I've fix the bug.

**Comment by hyunsik** [comment]
@jinossy I just reviewed your patch. The patch looks nice to me. BTW, could you trigger TravisCI?

**Comment by blrunner** [comment]
Hi @jinossy 

+1
Thanks for your great works. Tajo jdbc file looks pretty to me. 
And it integrated with JDBC support tools, such as SQL workbench, DbVisualizer.
If TravisCI build succeed, push it. :)

Cheers
Jaehwa

**Comment by blrunner** [comment]
For reference, all unit test cases finished successfully on my laptop.

**Comment by jinossy** [comment]
TravisCI failure is network issue of maven repository. 
I've just trigger the TravisCI and I'll commit it after CI is succeeded.

**Pull request closed without merging**
