### PR TITLE
TAJO-1269: Separate cli from tajo-client.

### PR DESCRIPTION
**Pull request by hyunsik**
This work separates tajo-cli from tajo-client. As a result, tajo-cli includes only cli tools and tsql. tajo-client contains only client API itself. In addition, TajoHAClientUtil checks the connectivity between client and master. This patch move the connectivity check to SessionConnection. So, I removed TajoHAClientUtil.

### CODE REVIEW

**Comment by jinossy** [comment]
You should add tajo-cli-module in tajo-dist maven plugin

**Comment by hyunsik** [comment]
@jinossy Thanks! I missed it. I'll add it.

**Comment by hyunsik** [comment]
@jinossy I just updated the tajo-dist/pom.xml.

**Comment by jinossy** [comment]
+1 LGTM
I'll fix the Unit test failure

**Pull request closed without merging**
