### PR TITLE
TAJO-1514: Distinguish UNION and UNION ALL

### PR DESCRIPTION
**Pull request by sirpkt**
This patch distinguishes UNION and UNION ALL, and implements UNION as UNION ALL + GROUP BY

UNION logical node with distinct flag is written as
Projection + Group by + Table Subquery + Union

It also fix test queries wrongly use union like union all

'mvn clean install' passed in my laptop

### CODE REVIEW

**Comment by hyunsik** [comment]
Unfortunately, I have enough time to review this patch. I'm sorry. I roughly looked over your approach. It looks nice to me.

**Comment by sirpkt** [comment]
Thank you for the comment, @hyunsik !
I always appreciate your devoted effort on our community,
so please don't feel sorry about that :)

**Comment by sirpkt** [comment]
rebased.

**Comment by hyunsik** [comment]
Hi @sirpkt,

Thank you for your work. I'm going to continue this work. I'm sorry for late review.

**Comment by hyunsik** [comment]
Even through it has very trivial conflict against the latest master branch, I can easily merge it to the latest master branch. The patch looks great to me. Here is my +1. I'll commit it shortly after I fix some trivial conflict. Thank you for your contribution.

**Comment by jihoonson** [comment]
+1 LGTM!

**Pull request closed without merging**
