### PR TITLE
TAJO-1900: When a record column and its child column are retrieved together, the record column might not be inferred as record type properly

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by jihoonson** [comment]
I verified my patch with 'mvn install'.

**Comment by hyunsik** [comment]
It seems to need rebase.

**Comment by jihoonson** [comment]
Rebased.

**Comment by jihoonson** [comment]
I've verified with 'mvn clean install' with jdk7.

**Comment by hyunsik** [comment]
+1 The patch looks straightforward.

**Comment by jihoonson** [comment]
Thanks for your review.

**Pull request closed without merging**
