### PR TITLE
TAJO-1960: Separate HDFS space handler and S3 space handler

### PR DESCRIPTION
**Pull request by blrunner**
I implemented ```S3TableSpace``` by copying ```FileTableSpace``` and added some unit test cases. But I've yet to test this patch on AWS.

### CODE REVIEW

**Comment by blrunner** [comment]
I've finished the test successfully on AWS as following:

* Tajo version: Use branch-0.11.1 because EMR default version for JDK is JDK 1.7. You can see codes for branch-0.11.1 at https://github.com/blrunner/tajo/tree/TAJO-1960-branch-0.11.1 .
* EMR version: 4.1.0
* DataSet : TPC-H 1G
* Bootstrap : 
```
aws emr create-cluster \
    --name="<cluster_name>" \
    --release-label=emr-4.1.0 \
    --no-auto-terminate \
    --use-default-roles \
    --ec2-attributes KeyName=<userId> \
    --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.xlarge InstanceGroupType=CORE,InstanceCount=3,InstanceType=c3.xlarge \
    --bootstrap-action Name="Install tajo",Path=s3://tajo-emr/emr-4.x/install-tajo.py,Args=["-t","<tarball_path>","-c","s3://tajo-emr/tajo-0.11.0/template/c3.xlarge/conf"]
```

**Comment by hyunsik** [comment]
I have a question. Is it just copied from FileTablespace? or you changed some code.

**Comment by blrunner** [comment]
Hi @hyunsik 

I just copied from FileTableSpace.

**Comment by blrunner** [comment]
I found that the patch runs as expected with master branch on EMR.

**Comment by hyunsik** [comment]
+1
@blrunner Ship it. The patch looks good to me.

**Pull request closed without merging**
