### PR TITLE
TAJO-1439: Wrong method name is fixed

### PR DESCRIPTION
**Pull request by eminency**
Pretty much trivial :)

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Hi, sorry for asking check again. Could you see my comment, please? I don't know the reason.

https://github.com/apache/tajo/commit/3aaff387c29adf1949d0a6ac4f0d6d7c7388f238

**Comment by eminency** [comment]
@dongjoon-hyun I'm working on it.

**Comment by dongjoon-hyun** [comment]
@eminency Thank you!

**Comment by eminency** [comment]
@dongjoon-hyun To track it, I created another JIRA ticket right before : https://issues.apache.org/jira/browse/TAJO-1440
It looks like a different problem.

**Comment by dongjoon-hyun** [comment]
@eminency Thank you for spending your time during weekend. I see.

**Pull request closed without merging**
