### PR TITLE
TAJO-1270 Fix typos

### PR DESCRIPTION
**Pull request by charsyam**
Fix typos for tajo files
Major Change:
in DefaultTajoCliOutputFormatter.java
change function name:
setScirptMode -> setScriptMode

### CODE REVIEW

**Comment by blrunner** [comment]
Sorry for my late review.
I also agree with @hyunsik's opinion and current words looks good compare than the full name.

**Comment by charsyam** [comment]
@blrunner @hyunsik I changed interim to intermididate :)

**Comment by hyunsik** [comment]
+1

**Comment by hyunsik** [comment]
Thank you @charsyam for your work :)

**Pull request closed without merging**
