### PR TITLE
TAJO-1452: Improve function listing order

### PR DESCRIPTION
**Pull request by dongjoon-hyun**

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by dongjoon-hyun** [comment]
It's strange. I tested with the same command with Travis CI. But, here, Travis CI fails with 'ERROR: org.apache.tajo.util.history.HistoryWriter (writeHistory(318)) - Error while saving query history: q_1427976531200_0529:Filesystem closed'. Anyway, I will test again in my desktop.

**Comment by hyunsik** [comment]
Hi @dongjoon-hyun,

Unfortunately, I don't have enough time to review this patch. Nevertheless, I greatly appreciate your recent contributions.

Besides, I'm going to give you some useful suggestion. You may close the previous PR (https://github.com/apache/tajo/pull/469) and open this PR in order to rebase or update the patch.

Actually, you don't need to close and open new PR for each update. You can update an existing PR by just pushing some changes to the branch used for the existing PR. I hope that my advice would be helpful to your contribution.

**Comment by dongjoon-hyun** [comment]
Thank you, @hyunsik ! As I mentioned in Jira, I will update the previous PR from now.

**Comment by dongjoon-hyun** [comment]
Travis CI error looks temporal error in Travis CI system. I tested with the same command with Travis CI, and the pass result file is in the following link.

https://app.box.com/s/d6pz3ocmigno6dzfrcy3eqoz44215lj7

**Comment by dongjoon-hyun** [comment]
Rebased.

**Comment by hyunsik** [comment]
+1
The change looks straightforward and reasonable. I'll commit it shortly.

**Pull request closed without merging**
