### PR TITLE
TAJO-1629: Sleep() function does not work.

### PR DESCRIPTION
**Pull request by jihoonson**
[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/591)

### CODE REVIEW

**Comment by blrunner** [comment]
+1

It looks good to me.

**Comment by jihoonson** [comment]
@blrunner thanks for your review, but I'll close this PR.
I think that we should find a better solution rather than this way because this patch will create a new thread per row and per sleep() function. 
Honestly, I forgot to withdraw this PR. Very sorry.

**Comment by blrunner** [comment]
Okay, no problem. :)

**Comment by jihoonson** [comment]
Thanks.

**Pull request closed without merging**
