### PR TITLE
TAJO-1414 Two RemoteException in rpc module

### PR DESCRIPTION
**Pull request by navis**
trivial

### CODE REVIEW

**Comment by ykrips** [comment]
My bad. When travis ci build has finished, this patch will be merged into main branch.

**Comment by ykrips** [comment]
Can you remove exception in tajo-rpc-protobuf module? This exception is common class and it could be used in rest module in future.

**Comment by navis** [comment]
ok, sure.

**Comment by ykrips** [comment]
+1.
Though travis ci buils is still in progress, but Maven build has succeeded on my local machine.
```
[INFO] Reactor Summary:
[INFO] 
[INFO] Tajo Main .......................................... SUCCESS [  1.726 s]
[INFO] Tajo Project POM ................................... SUCCESS [  0.975 s]
[INFO] Tajo Maven Plugins ................................. SUCCESS [  3.163 s]
[INFO] Tajo Common ........................................ SUCCESS [ 18.845 s]
[INFO] Tajo Algebra ....................................... SUCCESS [  1.381 s]
[INFO] Tajo Catalog Common ................................ SUCCESS [  6.270 s]
[INFO] Tajo Plan .......................................... SUCCESS [  5.521 s]
[INFO] Tajo Rpc Common .................................... SUCCESS [  0.448 s]
[INFO] Tajo Protocol Buffer Rpc ........................... SUCCESS [ 20.159 s]
[INFO] Tajo Catalog Client ................................ SUCCESS [  1.596 s]
[INFO] Tajo Catalog Server ................................ SUCCESS [01:19 min]
[INFO] Tajo Storage Common ................................ SUCCESS [  9.753 s]
[INFO] Tajo HDFS Storage .................................. SUCCESS [ 42.392 s]
[INFO] Tajo HBase Storage ................................. SUCCESS [  3.377 s]
[INFO] Tajo PullServer .................................... SUCCESS [  1.364 s]
[INFO] Tajo Client ........................................ SUCCESS [  2.590 s]
[INFO] Tajo CLI tools ..................................... SUCCESS [  0.919 s]
[INFO] Tajo JDBC Driver ................................... SUCCESS [  2.320 s]
[INFO] ASM (thirdparty) ................................... SUCCESS [  0.531 s]
[INFO] Tajo Catalog Drivers HCatalog ...................... SUCCESS [ 30.270 s]
[INFO] Tajo Core .......................................... SUCCESS [11:57 min]
[INFO] Tajo RESTful Container ............................. SUCCESS [  3.161 s]
[INFO] Tajo RPC ........................................... SUCCESS [  0.041 s]
[INFO] Tajo Catalog Drivers ............................... SUCCESS [  0.042 s]
[INFO] Tajo Catalog ....................................... SUCCESS [  0.106 s]
[INFO] Tajo Storage ....................................... SUCCESS [  0.057 s]
[INFO] Tajo Distribution .................................. SUCCESS [  0.639 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:55 min
[INFO] Finished at: 2015-03-20T10:27:09+09:00
[INFO] Final Memory: 92M/749M
[INFO] ------------------------------------------------------------------------
```

**Pull request closed without merging**
