### PR TITLE
TAJO-1413: tsql should not print a stacktrace message of not critical exceptions

### PR DESCRIPTION
**Pull request by dongjoon-hyun**
Trivial patch.

### CODE REVIEW

**Comment by dongjoon-hyun** [comment]
First, change `default setting` to hide stack trace.
Second, when printing stack tracing. Remove enclosing ServiceException.
*Before*
```
default> \d table2
ERROR: no such a table: table2
com.google.protobuf.ServiceException: java.sql.SQLException: ERROR: no such a table: table2
	at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:104)
	at org.apache.tajo.client.CatalogAdminClientImpl.getTableDesc(CatalogAdminClientImpl.java:216)
	at org.apache.tajo.client.TajoClientImpl.getTableDesc(TajoClientImpl.java:217)
	at org.apache.tajo.cli.tsql.commands.DescTableCommand.invoke(DescTableCommand.java:50)
	at org.apache.tajo.cli.tsql.TajoCli.executeMetaCommand(TajoCli.java:471)
	at org.apache.tajo.cli.tsql.TajoCli.executeParsedResults(TajoCli.java:445)
	at org.apache.tajo.cli.tsql.TajoCli.runShell(TajoCli.java:419)
	at org.apache.tajo.cli.tsql.TajoCli.main(TajoCli.java:694)
Caused by: java.sql.SQLException: ERROR: no such a table: table2
	at org.apache.tajo.client.CatalogAdminClientImpl$9.call(CatalogAdminClientImpl.java:231)
	at org.apache.tajo.client.CatalogAdminClientImpl$9.call(CatalogAdminClientImpl.java:217)
	at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:94)
	... 7 more
```
*After*
```
default> \d table2
ERROR: no such a table: table2
java.sql.SQLException: ERROR: no such a table: table2
	at org.apache.tajo.client.CatalogAdminClientImpl$9.call(CatalogAdminClientImpl.java:231)
	at org.apache.tajo.client.CatalogAdminClientImpl$9.call(CatalogAdminClientImpl.java:217)
	at org.apache.tajo.rpc.ServerCallable.withRetries(ServerCallable.java:94)
	at org.apache.tajo.client.CatalogAdminClientImpl.getTableDesc(CatalogAdminClientImpl.java:216)
	at org.apache.tajo.client.TajoClientImpl.getTableDesc(TajoClientImpl.java:217)
	at org.apache.tajo.cli.tsql.commands.DescTableCommand.invoke(DescTableCommand.java:50)
	at org.apache.tajo.cli.tsql.TajoCli.executeMetaCommand(TajoCli.java:471)
	at org.apache.tajo.cli.tsql.TajoCli.executeParsedResults(TajoCli.java:445)
	at org.apache.tajo.cli.tsql.TajoCli.runShell(TajoCli.java:419)
	at org.apache.tajo.cli.tsql.TajoCli.main(TajoCli.java:697)
```

**Comment by dongjoon-hyun** [comment]
Hi, @hyunsik . Could you describe *critical* exception a little bit more? I think I need to do more for this issue, but I have no criteria. Do you mean other exceptions except SQLException?

**Comment by jihoonson** [comment]
I don't think this issue is trivial. 
You might already consider, but we need to decide which errors are critical or trivial. 
IMO, we can regard the errors caused by users' mistake as trivial ones. For example, getting table meta of non-existing table might be user's mistake. 
Any other errors should be regarded as critical errors, and must be exposed to users to help to find what caused the problems. So, the default configuration must be reverted.

**Comment by dongjoon-hyun** [comment]
@jihoonson , Thank you for your comment. Now, I see the policy more clearly than before. I will revert the default configuration and add more case-by-case error handling code according to your opinion. Also, I will keep my eyes on this issue.

**Comment by dongjoon-hyun** [comment]
In TSQL commands, I found the following 4 trivial error patterns and suppress them. I think those cases covers almost trivial user errors.  

```
+        if (e instanceof IllegalArgumentException) {
+          onError(e.getMessage() == null ? "ERROR: Illegal Argument" : e.getMessage(), null);
+        } else if (e instanceof IOException && invoked instanceof ExecExternalShellCommand) {
+          onError(e.getMessage(), null);
+        } else if (e.getCause() instanceof SQLException) {
+          SQLException se = (SQLException) e.getCause();
+          onError(se.getMessage(), null);
+        } else {
+          onError(null, e);
+        }
```

**Pull request closed without merging**
