### PR TITLE
TAJO-1506: WorkerConnectionInfo::id field may be not unique, but its uniqueness is assumed throughout codes.

### PR DESCRIPTION
**Pull request by ykrips**

### CODE REVIEW

**Comment by ykrips** [comment]
Thanks to @blrunner test, this worker id generator moved to a resource tracker. Code modification has finished.

**Comment by blrunner** [comment]
@ykrips 

You're welcome. Please feel free to proceed this. :)

**Comment by ykrips** [comment]
@blrunner ,
Well, my work on this task already finished, but found that testcase result on jenkins build server and my laptop are completely different. I will keep track on why testcase failed on jenkins build server.

**Comment by blrunner** [comment]
@ykrips 

Thanks for your sharing. If you finish it, keep in touch anytime. :)

**Comment by ykrips** [comment]
I have run tajo core testcases on my laptop, and unable to find any suspect on this failure. I feel that it needs more time to investigate this issue. It might be related to TAJO-1526 task, and keep looking at it and leave a comment when I found a clue.

**Pull request closed without merging**
