### PR TITLE
TAJO-1357: Resolve findbugs warnings on Tajo Catalog Modules

### PR DESCRIPTION
**Pull request by ykrips**

### CODE REVIEW

**Comment by jinossy** [comment]
Could you upload the patch to jira? Because TajoQA can execute findbug

**Comment by ykrips** [comment]
Sure. No problems.:)

**Comment by jinossy** [comment]
+1
LGTM!

**Comment by ykrips** [comment]
Thank you for quick review. This commit will upload into master branch.

**Pull request closed without merging**
