### PR TITLE
TAJO-1701: Remove forward or non-forward query concept in TajoClient.

### PR DESCRIPTION
**Pull request by hyunsik**
[Review on Reviewable](https://reviewable.io/reviews/apache/tajo/645)

### CODE REVIEW

**Comment by hyunsik** [comment]
This patch simplified the code path to fetch query result data. This patch is ready to be reviewed.

**Comment by hyunsik** [comment]
I just rebased against the latest revision.

**Comment by jinossy** [comment]
@hyunsik rebase please?

**Comment by hyunsik** [comment]
I just rebased. It was just a conflict in changelog. You can review it now :)

**Comment by jinossy** [comment]
+1 LGTM!!

**Pull request closed without merging**
