### PR TITLE
TAJO-1335: Bump up 0.10.0-SNAPSHOT to 0.11.0-SNAPSHOT in master branch.

### PR DESCRIPTION
**Pull request by hyunsik**

### CODE REVIEW

**Comment by jinossy** [comment]
Could you update the tajo-cli module ?

**Comment by hyunsik** [comment]
This patch should rebase against the latest revision. I'll update the patch soon.

**Comment by hyunsik** [comment]
rebased.

**Comment by hyunsik** [comment]
Could anyone review this?

**Comment by jihoonson** [comment]
Sorry for late review. 
I 'll review tonight.

**Comment by jihoonson** [comment]
+1, ship it!

**Pull request closed without merging**
