### PR TITLE
TAJO-1823: Can't start TajoMaster.

### PR DESCRIPTION
**Pull request by hyunsik**

### CODE REVIEW

**Comment by jinossy** [comment]
Thanks for your quick fix but I can't compile on IDE
The problem looks like that incorrect generated source path and module order.

Could you create the package directory ?
```
tajo-sql-parser/src/main/antlr4/org.apache.tajo.parser.sql
```

Please change module order as follows : 
```
...
<module>tajo-algebra</module>
<module>tajo-sql-parser</module>
...
```

**Comment by hyunsik** [comment]
Thank you for the comment. I'll check out them.

**Comment by hyunsik** [comment]
I fixed the wrong package name and rebased the patch.

**Comment by jinossy** [comment]
+1

**Pull request closed without merging**
