### PR TITLE
TAJO-1908: Add a link to the nightly build version to the download page

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by hyunsik** [comment]
Could you add some kind of disclaimer about stability? An example is 'The nightly version comes from the current development branch. Note that this version may include unstable features and unknown bugs.'

**Comment by jihoonson** [comment]
How about adding it to the wiki page (https://cwiki.apache.org/confluence/display/TAJO/Nightly+Builds)?

**Comment by hyunsik** [comment]
Unless you add direct download link on the web, your suggestion sounds good to me.

**Comment by jihoonson** [comment]
Thanks. I've added the disclaimer to the wiki page.

**Comment by hyunsik** [comment]
+1 
Looks good to me.

**Comment by jihoonson** [comment]
Thanks for your review.

**Pull request closed without merging**
