### PR TITLE
TAJO-1815: Catalog store initialization with PostgreSQL failed

### PR DESCRIPTION
**Pull request by eminency**
Duplicated primary key definition removed.

### CODE REVIEW

**Comment by hyunsik** [comment]
+1

**Comment by hyunsik** [comment]
I missed to close this issue. Could you close this ticket?

**Comment by hyunsik** [comment]
It was committed in ea4443d8df6ffb02e328304dc5681dbd54f62501.

**Comment by eminency** [comment]
Sure, thank you for the review.

**Pull request closed without merging**
