### PR TITLE
TAJO-1904: Extend GraphVisitor to accept user-defined context

### PR DESCRIPTION
**Pull request by jihoonson**

### CODE REVIEW

**Comment by hyunsik** [comment]
Could you rebase it?

**Comment by jihoonson** [comment]
Rebased.

**Comment by hyunsik** [comment]
+1
The patch looks good to me. This feature has been necessary. I manually verified 'mvn clean install'. All unit tests are passed.

**Comment by jihoonson** [comment]
@hyunsik, thanks for your review. I've committed.

**Pull request closed without merging**
